# oscam.conf generated automatically by Streamboard OSCam 2.26.02-11945
# Read more: https://git.streamboard.tv/common/oscam/blob/master/Distribution/doc/txt/oscam.conf.txt

[global]
logfile                       = /var/log/oscam.log

[streamrelay]
stream_relay_enabled          = 1
stream_relay_user             = tvheadend
stream_relay_ctab             = 098C,098D,09C4
stream_relay_buffer_time      = 100

[dvbapi]
enabled                       = 1
au                            = 1
pmt_mode                      = 0
listen_port                   = 9000
user                          = tvheadend
boxtype                       = pc

[webif]
httpport                      = 8888
httpuser                      = admin
httppwd                       = admin
httpallowed                   = 0.0.0.0-255.255.255.255

